apiVersion: v1
kind: Namespace
metadata:
  name: irsa-demo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamodb-sa
  namespace: irsa-demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::191072690914:role/dynamodb-irsa-role