apiVersion: v1
kind: Namespace
metadata:
  name: customer-app

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dynamodb-sa
  namespace: customer-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::191072690914:role/dynamodb-irsa-role