apiVersion: v1
kind: Secret

metadata:
  name: {{ .Release.Name }}-secret

type: Opaque

stringData:
  DB_USERNAME: "{{ .Values.secret.DB_USERNAME }}"
  DB_PASSWORD: "{{ .Values.secret.DB_PASSWORD }}"