apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: app-secret

  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: my-app-secret
      property: DB_USERNAME

  - secretKey: DB_PASSWORD
    remoteRef:
      key: my-app-secret
      property: DB_PASSWORD

  - secretKey: JWT_SECRET
    remoteRef:
      key: my-app-secret
      property: JWT_SECRET